# Generated by Django 4.2 on 2023-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Your_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('person', models.CharField(choices=[('person1', 'person1'), ('person2', 'person2'), ('person3', 'person3'), ('person4', 'person4')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('narxi', models.PositiveIntegerField()),
                ('nomi', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('coffee_turi', models.CharField(choices=[('Issiq', 'Issiq'), ('Sovuq', 'Sovuq')], max_length=20)),
            ],
        ),
    ]
